### ISSUE TITLE
ci: update dependabot commit messages

### ISSUE THREAD

**Issue by davidlday** [prosegrinder/annotatedtext#370]
Update 

```yaml
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
```
